### ISSUE TITLE
relaxing assertion newmember memo signature after rule application must equal to existing members

### ISSUE THREAD

**Issue by zhouqingqing** [zhouqingqing/qpmodel#143]
This is good for assertion but not good to introduce certain transform rules.

Consider this:

```Limit->Agg->shuffle->scan```

we can transform with globalAgg+localAgg rule against "Agg" group:

```Limit->GlobalAgg->shuffle->LocalAgg->scan```

However, the newly generated "GlobalAgg" subtree does not have the same signature as the original "Agg" subtree - for exampe: "Agg" is count(*), then "GlobalAgg" shall be sume(local_count(*)).

Currently we assert newmember memo signature must equal to existing members, so we can insert the newmember to the group list. Once we relax it, we insert into the gorup list if they have same signature, otherwise create a new group and fixing the orginal group's parent so they can reference it.

Other details:
- the original group's parent may have multiple
- if we again apply the "anti-rule" (for above example, is merge_global_local_to_agg rule), we will generate duplicate group as original group, but memo will not allow it to insert.

**Comment by arzuschen** [comment]
The assertion that members within the same memo group must have the same signature does not need to be relaxed.
For the newly created global aggregate-local aggregate pair, the new global shall be in the same group as the old aggregate. This can be achieved by forcing the new one have the same signature as the original one. 
Meanwhile, the local aggregate need to be placed in a new group, this process requires identification that the node does not belong to the old aggregate group. Lifting the assertion may result in more unnecessary change to the whole exploration process.
Additionally, the property enforced nodes are added to the group after exploration. Even though the signature is different, it does not conflict with the validation step during exploration.

**Comment by zhouqingqing** [comment]
closed as not needed
