### ISSUE TITLE
[bug] race condition in emulated distributed execution

### ISSUE THREAD

**Issue by zhouqingqing** [zhouqingqing/qpmodel#173]
Test case Redistribute(), which does not reliably repro but you can make it easy to repro with a endless loop:

```
       public void Redistribute()
        {
            for (; ; )
            {
                // needs order by to force result order
                var phyplan = "";
```

when it is fixed, change for(;;) to 3 times.

**Comment by zhouqingqing** [comment]
@zhouruiapple updates?

**Comment by zhouruiapple** [comment]
@zhouqingqing In progressing right now

**Comment by zhouruiapple** [comment]
@zhouqingqing Can you explain the bug with more information? I don't find the race condition in the code of Redistribute().

**Comment by zhouqingqing** [comment]
Have you tried putting the loop around the unittest? -------- Original message --------From: zhourui <notifications@github.com>Date: Mon, Aug 10, 2020, 19:31To: zhouqingqing/qpmodel <qpmodel@noreply.github.com>Cc: Qingqing Zhou <zhouqq.github@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [zhouqingqing/qpmodel] [bug] race condition in emulated distributed execution (#173)
@zhouqingqing Can you explain the bug with more information? I don't find the race condition in the code of Redistribute().

**Comment by zhouqingqing** [comment]
another issue is profiling nodes actual rows = 0.

Check out here:
https://github.com/zhouqingqing/qpmodel/pull/187/files

Look at tpch query plans with actual stats. You can see many with "actual rows = 0" under gather. I think what's happened here is that each individual threads have do their profiling correctly but there is no process to "summarize" profilings into the main thread's profiling nodes, so we see all zeros.

**Comment by zhouqingqing** [comment]
another issue by testing TestTpchDistributed()

Put a for(;;) loop around line 413, you shall repro an issue with the cached subquery

(actual rows, loops = 2)

where loops = 2 is extra garbage. Most likely Q16.

**Comment by zhouruiapple** [comment]
@zhouqingqing Got it.

**Comment by zhouruiapple** [comment]
The @totalfreq_ of @MCVList of ColumnStat cause EstSelectivity which return different value when unit test issued. Is it changed in different threads? @zhouqingqing

**Comment by zhouqingqing** [comment]
check out how ANALYZE is implemented - there is a GATHER on top of select statement, so analyze itself is not multi-threaded.

**Comment by zhouruiapple** [comment]
@zhouqingqing ths. This is the only problem left. I will fix it as soon as possible.
