### ISSUE TITLE
[bug] unstable ANALYZE results on distributed tables (with MEMO)

### ISSUE THREAD

**Issue by zhouqingqing** [zhouqingqing/qpmodel#193]
Occasionally we see distributed tpch query (Q5, Q10) failed due to different cost estimation:

![image](https://user-images.githubusercontent.com/29663431/90442658-db280680-e08f-11ea-9122-8ec050e86f8a.png)

One root cause is the bottom scan CE:

```
    expected: -> PhysicScanTable orders (inccost=1500, cost=1500, rows=225) (actual rows=0)  
    actual:   -> PhysicScanTable orders (inccost=1500, cost=1500, rows=224) (actual rows=0)
```

This shall be rooted in unstable ANALYZE results on distributed tables.

**Comment by zhouqingqing** [comment]
https://github.com/zhouqingqing/qpmodel/commit/75ea645496b4366bc9cc817ca50c65dec0cbbd7b failed due to the same issue:

![image](https://user-images.githubusercontent.com/29663431/90553284-fd318f80-e148-11ea-90c5-955c2ee96184.png)

**Comment by zhouruiapple** [comment]
This bug has been fix in bug [https://github.com/zhouqingqing/qpmodel/issues/173](https://github.com/zhouqingqing/qpmodel/issues/173). Pls see commit [https://github.com/zhouqingqing/qpmodel/pull/198](https://github.com/zhouqingqing/qpmodel/pull/198).
