### ISSUE TITLE
where exists or exists exception

### ISSUE THREAD

**Issue by pkommoju** [zhouqingqing/qpmodel#213]
select a.a1 from a where exists (select * from b where a.a2 = b.b2) or exists (select * from c where a.a2 = c.c2) order by 1

fails because the first exists subquery has no physical plan, it is possible that the second one doesn't either.
When OR is changed to AND it produces correct results.

Another query which has an OR also fails.

select 1 from a where a.a1 > (select b1 from b where b.b2 > (select c2 from c where c.c2=b2) or b.b1 > ((select c2 from c where c.c2=b2)))

**Comment by zhouqingqing** [comment]
We didn't handle OR systematically

**Comment by 9DemonFox** [comment]
This is the cause of this issue. In practical, there should be no "or expression" in seme-join expression if you want to unnest the subquery.                       
 if (queryOpt_.optimize_.enable_subquery_unnest_)
                    {
                        // use the plan 'root' containing the subexpr 'x'
                        var replacement = oneSubqueryToJoin(root, x);
                        newroot = (LogicNode)newroot.SearchAndReplace(root,
                                                                replacement);
                    }

**Comment by 9DemonFox** [comment]
Blow is the plan of SQL(explain
select
a.a1
from a
where
exists
(select * from b where a.a2 = b.b2)
**and** exists
(select * from c where a.a2 = c.c2)
clearly, it was unnested .
![image](https://user-images.githubusercontent.com/37564807/93607455-eb6b3280-f9fb-11ea-8dce-ef4a29b23b08.png)

**Comment by 9DemonFox** [comment]
During handling this issue. I find another issue.
"select a.a1 from b" will return result "null" instead if Error, 
Maybe it needs to open anothor issue if necessary.

**Comment by pkommoju** [comment]
This is very bad. I mean unnest or otherwise returning correct results even if it is  slow if preferable than returning outrageously incorrect results. I will open an issue and assign it to myself.

**Comment by zhouqingqing** [comment]
>  In practical, there should be no "or expression" in semi-join expression if you want to unnest the subquery.

This is not true. The sub-query related papers explicitly give examples the transformations with singlejoin can handle OR.

> Blow is the postgreSQL's plan of SQL

We shall get the same PG plan with enable_subquery_unnest_ = false. PG can't do complex subquery decorrelation as us.

**Comment by 9DemonFox** [comment]
> The paper _Unnesting Arbitrary Queries_ 
> To the best of our knowledge, no existing system can unnest such a query. And indeed, unnesting this query is hard:
The routine of oneSubqueryToJoin(root, x) indeed doesn't process the situation of "or expression" in subquery as @zhouqingqing  refered.
> We didn't handle OR systematically
I  originally think the issue is just the problem of  "when there is a or in subquey, we don't need to unnest it". 
So I have to read this paper to understand and realize it.

**Comment by zhouqingqing** [comment]
@9DemonFox where are we with this issue?

**Comment by 9DemonFox** [comment]
I take over this issue from zhourui today. And locate the codes causing this BUG as bellow.
```
            LogicFilter Filter = new LogicFilter(markjoin, topfilter);
```
![20201026-142208(eSpace)](https://user-images.githubusercontent.com/37564807/97139999-b8ecec00-1796-11eb-84af-eb85bda89124.jpg)
it wil handel @1 OR @2 to the plan to the Fig A, i.e. embedding the @2 to a lower level. For AND, it will be ok to do so. 
I try to handle it to the plan like Fig B.

**Comment by zhouqingqing** [comment]
agree fig B is the right plan.
