### ISSUE TITLE
what if  x.query_.physicPlan_ is null here, it's a bug should be fixed

### ISSUE THREAD

**Issue by 9DemonFox** [zhouqingqing/qpmodel#230]
if (this.logic_.filter_ != null)
            {
                Expr expr = this.logic_.filter_;
                expr.VisitEachT<SubqueryExpr>(x =>
                {
                    if (x.query_.physicPlan_ != null)
                    {
                        var phynode = x.query_.physicPlan_ as PhysicNode;
                        incCost += phynode.InclusiveCost();
                    }
                }
                );
            }

**Comment by zhouqingqing** [comment]
do you have a test case that x.query_.physicPlan_ is null?

**Comment by 9DemonFox** [comment]
@zhouqingqing ,  I don't really figure out what kind  of sql statements can use to create this  test case.  Could you please give me an example?

**Comment by zhouqingqing** [comment]
If you believe there is no case can have "x.query_.physicPlan_ is null", then you shall change it to "Debug.Assert(x.query_.physicPlan_ != null)".

**Comment by zhouqingqing** [comment]
use assertion instead 7b5ce91c516afef9283a6759b090b87738495b28
