### ISSUE TITLE
# NOT IN subquery Logic

### ISSUE THREAD

**Issue by 9DemonFox** [zhouqingqing/qpmodel#246]

**Comment by 9DemonFox** [comment]
[postgres-not-in-null-gives-no-result](https://stackoverflow.com/questions/17877100/postgres-not-in-null-gives-no-result)
if we have follow the logic of PostgreSQL.

**Comment by zhouqingqing** [comment]
@pkommoju any comments?

**Comment by pkommoju** [comment]
NULL comparison only works with x IS NULL and x IS NOT NULL. Only in these cases the result is TRUE or FALSE depending on x being NULL or NOT NULL. Every other way of comparing something against NULL results in NULL. This standard SQL and Postgres follows the standard. We should do the same.

**Comment by pkommoju** [comment]
NULL = NULL is NULL, and so is NULL <> NULL.
