### ISSUE TITLE
Migrate to dotnet core

### ISSUE THREAD

**Issue by dovahcrow** [zhouqingqing/qpmodel#93]
Currently, the project is depending on the Windows ONLY `.net framework`. For the sake of widespread adoption and community friendliness, I suggest migrating the project to `.net core`.

Migration guide: https://docs.microsoft.com/en-us/dotnet/core/porting/

However, the migration process can change the project settings and will have some hurdles to the current development early on. 

Let me know if you want to go in this direction. I can help with this issue and try to make the migration process as smooth as possible.

**Comment by zhouqingqing** [comment]
Thanks - I'd love to see it with. net core. We may have references only available in. net framework like the CSV reader (not sure though), but shall not be terribly difficult to remove them.
